#!/usr/bin/env python3

name = 'Alan'
age  = 42

print('Hello, world. My name is {}, and I am {}'.format(name, age))

if age < 12:
    print('You are a child')
elif age < 20:
    print('You are a teen')
elif age < 30:
    print('You are in your twenties')
elif age == 100:
    print('You are a century old')
else:
    print('You are older than 30')